# Generated by Django 5.1.7 on 2025-03-18 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trendingnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_of_publish',
            field=models.DateTimeField(default=datetime.date(2025, 3, 19)),
        ),
    ]
