# Generated by Django 5.1.7 on 2025-03-18 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_date_of_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
