# Generated by Django 5.1.7 on 2025-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_created_alter_news_date_of_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
